-- =========================================================================
-- KỊCH BẢN KHỞI TẠO CƠ SỞ DỮ LIỆU ĐỒNG BỘ AN TOÀN TOÀN DIỆN (IDEMPOTENT SQL)
-- CHẠY NHIỀU LẦN KHÔNG BAO GIỜ BỊ LỖI DUPLICATE/42710
-- =========================================================================

-- 1. Bảng Sản phẩm (products)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    sales_count INT NOT NULL DEFAULT 0,
    shop_type TEXT NOT NULL DEFAULT 'RETAIL',
    shop_name TEXT NOT NULL DEFAULT 'TQ Store',
    image_url TEXT,
    details TEXT,
    stock INT NOT NULL DEFAULT 10,
    badge TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Bảng Đơn hàng (orders)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    user_email TEXT NOT NULL,
    user_name TEXT,
    total_amount NUMERIC NOT NULL DEFAULT 0,
    payment_method TEXT NOT NULL DEFAULT 'wallet',
    shipping_address TEXT,
    status TEXT NOT NULL DEFAULT 'completed',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Bảng Chi tiết Đơn hàng (order_items)
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT,
    product_name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    quantity INT NOT NULL DEFAULT 1,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Bảng Nhắn tin Thời gian thực (messages)
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    user_email TEXT NOT NULL,
    user_name TEXT,
    content TEXT NOT NULL,
    sender_role TEXT NOT NULL DEFAULT 'customer',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Bảng Thông Báo Toàn Hệ Thống do Admin Phát Hàng (system_announcements)
CREATE TABLE IF NOT EXISTS public.system_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT DEFAULT 'ANNOUNCEMENT',
    badge TEXT DEFAULT '📢 THÔNG BÁO MỚI',
    is_active BOOLEAN DEFAULT TRUE,
    created_by TEXT DEFAULT 'Super Admin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Bảng Cấu hình Giao diện & Hệ thống Realtime (tq_platform_config)
CREATE TABLE IF NOT EXISTS public.tq_platform_config (
    id INT PRIMARY KEY DEFAULT 1,
    system_theme JSONB DEFAULT '{
      "id": "dark_luxury",
      "theme_name": "dark_luxury",
      "name": "🌙 Đêm Sang Trọng (Luxury Dark)"
    }'::jsonb,
    shop_settings JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- BẬT TÍNH NĂNG REALTIME AN TOÀN CHỐNG LỖI 42710
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'messages'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'system_announcements'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.system_announcements;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'tq_platform_config'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.tq_platform_config;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'orders'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
    END IF;
END $$;

-- BẢO MẬT CÁC BẢNG QUA ROW LEVEL SECURITY (RLS POLICIES)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tq_platform_config ENABLE ROW LEVEL SECURITY;

-- CÁC CHÍNH SÁCH BẢO MẬT RLS (XOÁ CŨ NẾU CÓ ĐỂ TRÁNH TRÙNG LẮP)
DROP POLICY IF EXISTS "Allow public read products" ON public.products;
DROP POLICY IF EXISTS "Allow public insert products" ON public.products;
DROP POLICY IF EXISTS "Allow public update products" ON public.products;
DROP POLICY IF EXISTS "Users read own orders" ON public.orders;
DROP POLICY IF EXISTS "Users insert own orders" ON public.orders;
DROP POLICY IF EXISTS "Allow read order items" ON public.order_items;
DROP POLICY IF EXISTS "Allow insert order items" ON public.order_items;
DROP POLICY IF EXISTS "Allow public read messages" ON public.messages;
DROP POLICY IF EXISTS "Allow public insert messages" ON public.messages;
DROP POLICY IF EXISTS "Allow public read announcements" ON public.system_announcements;
DROP POLICY IF EXISTS "Allow admin insert announcements" ON public.system_announcements;
DROP POLICY IF EXISTS "Allow public read platform config" ON public.tq_platform_config;
DROP POLICY IF EXISTS "Allow admin update platform config" ON public.tq_platform_config;

CREATE POLICY "Allow public read products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow public insert products" ON public.products FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update products" ON public.products FOR UPDATE USING (true);

CREATE POLICY "Users read own orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Users insert own orders" ON public.orders FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow read order items" ON public.order_items FOR SELECT USING (true);
CREATE POLICY "Allow insert order items" ON public.order_items FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read messages" ON public.messages FOR SELECT USING (true);
CREATE POLICY "Allow public insert messages" ON public.messages FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read announcements" ON public.system_announcements FOR SELECT USING (true);
CREATE POLICY "Allow admin insert announcements" ON public.system_announcements FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read platform config" ON public.tq_platform_config FOR SELECT USING (true);
CREATE POLICY "Allow admin update platform config" ON public.tq_platform_config FOR ALL USING (true);
