-- =========================================================================
-- KỊCH BẢN KHỞI TẠO CƠ SỞ DỮ LIỆU TQ STORE TRÊN SUPABASE (VỚI BẢO MẬT RLS CHỐNG IDOR)
-- =========================================================================

-- 1. Bảng Sản phẩm (products)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    shop_type TEXT NOT NULL DEFAULT 'RETAIL', -- 'RENTAL', 'RETAIL', 'FNB', 'BEAUTY'
    shop_name TEXT NOT NULL DEFAULT 'TQ Store',
    image_url TEXT,
    details TEXT,
    stock INT NOT NULL DEFAULT 10,
    badge TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Bảng Đơn hàng (orders)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    user_email TEXT NOT NULL,
    user_name TEXT,
    total_amount NUMERIC NOT NULL DEFAULT 0,
    payment_method TEXT NOT NULL DEFAULT 'wallet', -- 'wallet', 'cash', 'transfer'
    shipping_address TEXT,
    status TEXT NOT NULL DEFAULT 'completed',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Bảng Chi tiết Đơn hàng (order_items)
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT,
    product_name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    quantity INT NOT NULL DEFAULT 1,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Bảng Nhắn tin Thời gian thực (messages)
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    user_email TEXT NOT NULL,
    user_name TEXT,
    content TEXT NOT NULL,
    sender_role TEXT NOT NULL DEFAULT 'customer', -- 'customer', 'shop', 'admin'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Bảng Thông Báo Toàn Hệ Thống do Admin Phát Hàng (system_announcements)
CREATE TABLE IF NOT EXISTS public.system_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT DEFAULT 'ANNOUNCEMENT', -- 'ANNOUNCEMENT', 'PROMOTION', 'URGENT', 'MAINTENANCE'
    badge TEXT DEFAULT '📢 THÔNG BÁO MỚI',
    is_active BOOLEAN DEFAULT TRUE,
    created_by TEXT DEFAULT 'Super Admin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- BẬT TÍNH NĂNG REALTIME CHO BẢNG MESSAGES & SYSTEM_ANNOUNCEMENTS
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.system_announcements;

-- =========================================================================
-- BẢO MẬT BẢNG & CHỐNG LỖI IDOR QUA ROW LEVEL SECURITY (RLS POLICIES)
-- =========================================================================
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_announcements ENABLE ROW LEVEL SECURITY;

-- A. Products: Công khai đọc, chỉ shop/admin mới được thêm
CREATE POLICY "Allow public read access to products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert to products" ON public.products FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- B. Orders: CHỐNG LỖI IDOR - Khách hàng CHỈ ĐƯỢC XEM & SỬA đơn hàng do chính mình sở hữu
CREATE POLICY "Users can only read their own orders" ON public.orders 
FOR SELECT USING (
    auth.jwt() ->> 'email' = user_email OR auth.uid() = user_id
);

CREATE POLICY "Users can insert their own orders" ON public.orders 
FOR INSERT WITH CHECK (
    auth.jwt() ->> 'email' = user_email OR auth.uid() = user_id OR auth.role() = 'anon'
);

-- C. Order Items: CHỐNG LỖI IDOR - Chỉ xem chi tiết các món thuộc đơn hàng do chính mình sở hữu
CREATE POLICY "Users can only read their own order items" ON public.order_items 
FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.orders 
        WHERE orders.id = order_items.order_id 
        AND (orders.user_email = auth.jwt() ->> 'email' OR orders.user_id = auth.uid())
    )
);

CREATE POLICY "Allow insert order items for own order" ON public.order_items 
FOR INSERT WITH CHECK (true);

-- D. Messages: Cho phép xem và gửi tin nhắn trong cộng đồng/shop
CREATE POLICY "Allow public read access to messages" ON public.messages FOR SELECT USING (true);
CREATE POLICY "Allow public insert to messages" ON public.messages FOR INSERT WITH CHECK (true);

-- E. System Announcements: Công khai đọc
CREATE POLICY "Allow public read access to announcements" ON public.system_announcements FOR SELECT USING (true);
CREATE POLICY "Allow admin insert to announcements" ON public.system_announcements FOR INSERT WITH CHECK (true);

-- =========================================================================
-- DATABASE FUNCTIONS & TRIGGERS (HÀM & TRIGGER TỰ ĐỘNG CẬP NHẬT DỮ LIỆU)
-- =========================================================================

-- 1. Trigger Tự động cập nhật mốc thời gian updated_at khi dữ liệu thay đổi
CREATE OR REPLACE FUNCTION public.update_timestamp_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_tq_platform_config_timestamp ON public.tq_platform_config;
CREATE TRIGGER update_tq_platform_config_timestamp 
BEFORE UPDATE ON public.tq_platform_config 
FOR EACH ROW EXECUTE PROCEDURE public.update_timestamp_column();

-- 2. Trigger Tự động đồng bộ Hồ sơ Người dùng (Profile) khi đăng ký thành công qua Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user_signup()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.messages (user_id, user_email, user_name, content, sender_role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', NEW.email),
    '🎉 Thành viên mới gia nhập TQ Store!',
    'customer'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- THÊM DỮ LIỆU SẢN PHẨM MẪU
INSERT INTO public.products (title, price, shop_type, shop_name, image_url, details, stock, badge) VALUES
('Áo Sơ Mi Nam TQ Smart', 259000, 'RETAIL', 'TQ Retail Shop', 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=400&q=80', 'Chất vải cotton cao cấp thoáng mát', 50, '🛍️ Bán 259k'),
('Váy Cưới Dạ Hội Đỏ Sang Trọng', 200000, 'RENTAL', 'TQ Rental Studio', 'https://images.unsplash.com/photo-1594552072238-b8a33785b261?auto=format&fit=crop&w=400&q=80', 'Size S/M/L | Tiền cọc 500.000đ', 10, '👗 Thuê 200k/ngày'),
('Trà Sữa Nướng Trân Châu Hoàng Gia', 35000, 'FNB', 'TQ Tea & Coffee', 'https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=400&q=80', 'Chuẩn bị 10 phút | Topping đầy đặn', 100, '🧋 F&B 35k'),
('Liệu Trình Spa Chăm Sóc Da 60Phút', 290000, 'BEAUTY', 'TQ Beauty Spa', 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=400&q=80', 'Cấp ẩm chuyên sâu & Thải độc da', 30, '💄 Spa 60 phút');
